/*
    --관리자 계정에서 JDBC 계정 생성, 권한 부여
    CREATE USER JDBC IDENTIFIED BY JDBC
    GRANT CONNECT, RESOURCE TO JDBC;
*/
CREATE USER JDBC IDENTIFIED BY JDBC;
GRANT CONNECT, RESOURCE TO JDBC;

----------------여기서부터는 JDBC계정에서 실행----------------

DROP TABLE MEMBER; --MEMBER테이블 삭제

CREATE TABLE MEMBER( --MEMBER테이블 생성
    USERNO NUMBER PRIMARY KEY,
    USERID VARCHAR2(20) UNIQUE NOT NULL,
    USERPWD VARCHAR2(20) NOT NULL,
    USERNAME VARCHAR2(20) NOT NULL,
    GENDER CHAR(1) CHECK (GENDER IN ('M','F')),
    AGE NUMBER,
    EMAIL VARCHAR2(30),
    PHONE VARCHAR2(20),
    ADDRESS VARCHAR2(200),
    HOBBY VARCHAR2(50),
    ENROLLDATE DATE DEFAULT SYSDATE NOT NULL
);
-------------컬럼명 변경----------------------------------
ALTER TABLE MEMBER RENAME COLUMN USERNO TO "학번";
ALTER TABLE MEMBER RENAME COLUMN USERID TO "아이디";
ALTER TABLE MEMBER RENAME COLUMN USERPWD TO "비밀번호";
ALTER TABLE MEMBER RENAME COLUMN USERNAME TO "이름";
ALTER TABLE MEMBER RENAME COLUMN GENDER TO "성별";
ALTER TABLE MEMBER RENAME COLUMN AGE TO "나이";
ALTER TABLE MEMBER RENAME COLUMN EMAIL TO "이메일";
ALTER TABLE MEMBER RENAME COLUMN PHONE TO "핸드폰";
ALTER TABLE MEMBER RENAME COLUMN ADDRESS TO "주소";
ALTER TABLE MEMBER RENAME COLUMN HOBBY TO "취미";
ALTER TABLE MEMBER RENAME COLUMN ENROLLDATE TO "등록일";
----------------------------------------------------------
SELECT * FROM MEMBER;--MEMBER테이블 조회

drop sequence SEQ_USERNO;--SEQ_USERNO시퀀스 삭제

CREATE SEQUENCE SEQ_USERNO--SEQ_USERNO시퀀스 생성
NOCACHE;




------------------------------------------------------------------





CREATE TABLE TEST(
    TNO NUMBER,
    TNAME VARCHAR2(20),
    TDATE DATE
);

DELETE FROM TEST;
ROLLBACK;

SELECT *
FROM TEST;


CREATE TABLE STUDENT(
    SNO NUMBER PRIMARY KEY,
    SNAME VARCHAR2(30) NOT NULL,
    SDATE DATE DEFAULT SYSDATE
);
ALTER TABLE STUDENT RENAME COLUMN SNO TO 학번;
ALTER TABLE STUDENT RENAME COLUMN SNAME TO 이름;
ALTER TABLE STUDENT RENAME COLUMN SDATE TO 등록날짜;
SELECT *
FROM STUDENT;

CREATE SEQUENCE SEQ_PHONE
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE TABLE PHONE (
    PNO NUMBER,
    PNAME VARCHAR2(30),
    PRICE NUMBER,
    PDATE DATE DEFAULT SYSDATE
);
ALTER TABLE PHONE RENAME COLUMN PNO TO 번호;
ALTER TABLE PHONE RENAME COLUMN PNAME TO 기종;
ALTER TABLE PHONE RENAME COLUMN PRICE TO 가격;
ALTER TABLE PHONE RENAME COLUMN PDATE TO 생산시점;

SELECT *
FROM PHONE;
drop sequence seq_phone;






